### ISSUE TITLE
Unprocessed items in batch writes

### ISSUE THREAD

**Issue by fxn** [ex-aws/ex_aws_dynamo#20]
Do you have any recommendations for dealing with unprocessed items returned by a batch write? ExAws has retry logic builtin, but I believe we do not have it integrated here right?

**Comment by darrenklein** [comment]
I'll have to dig into this a bit and check, but I'm fairly certain that you're correct, this library doesn't integrate ExAws' retry behaviors (again, I'll have to check that - I'm not the founder of this project, just acting as a maintainer, so I am not super-familiar with all of its workings).

For starters, I'd say that you might look to implement your own retry logic, based on Amazon's recommendations - https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_BatchWriteItem.html - the important bit being:

"If DynamoDB returns any unprocessed items, you should retry the batch operation on those items. However, we strongly recommend that you use an exponential backoff algorithm. If you retry the batch operation immediately, the underlying read or write requests can still fail due to throttling on the individual tables. If you delay the batch operation using exponential backoff, the individual requests in the batch are much more likely to succeed."

If ExAws supports retry logic and it seems like it would be appropriate to apply it in cases of unprocessed items, I'd say that's a feature that this repo should look to integrate, perhaps as some sort of configurable option - but this will all take a bit of research and thinking.

I'm super-busy right now, but sometime in the next few days, I'll put my mind to this a bit. If this looks like a good feature to support, I'd consider adding a "help wanted" flag to this and seeing if we could pick up any support from the community (or yourself, if you're so inclined).  Personally, I just don't have the time to go too deep on this right now.

**Comment by darrenklein** [comment]
Just thinking "out loud"/documenting a bit here - ExAws does implement retry logic - from that project's README:

## Retries

ExAws will retry failed AWS API requests using exponential backoff per the "Full
Jitter" formula described in
https://www.awsarchitectureblog.com/2015/03/backoff.html

The algorithm uses three values, which are configurable:

```elixir
# default values shown below

config :ex_aws, :retries,
  max_attempts: 10,
  base_backoff_in_ms: 10,
  max_backoff_in_ms: 10_000
```

* `max_attempts` is the maximum number of possible attempts with backoffs in between each one
* `base_backoff_in_ms` corresponds to the `base` value described in the blog post
* `max_backoff_in_ms` corresponds to the `cap` value described in the blog post

It seems to me that this behavior isn't exactly appropriate for handling `UnprocessedItems`/`UnprocessedKeys`, since in those cases, we don't want to retry the entire operation, just values that weren't handled. Furthermore, I'm not actually clear on the status code that would be found on a response with unprocessed resources (any insight into what those might be would be really helpful) - but if they were in the range of 200-299 or 304, they wouldn't get picked up by the retry logic anyway (take a look at `ExAws.Request` if you want to see what I mean).

My feeling is that we'd want to implement configurable retry logic that's similar to the way that retries are handled in ExAws, but specifically tailored to handle unprocessed resources.

@fxn I'd be curious to hear your thoughts on this.

**Comment by fxn** [comment]
Hey! Yes, that makes sense to me too.

**Comment by darrenklein** [comment]
After thinking about this issue some more, I'm not sure ExAws.Dynamo is the right place to handle retrying unprocessed items from batch operations (note that these may occur in batch read as well as batch write operations). This library seems to me to be a little too low-level for that, its job should probably just be to report any unprocessed items to the parent application (which it does) and let the parent deal with those as it will.

I'd certainly be open to discussion on this, but I'm closing the issue for now.

**Comment by fxn** [comment]
At this point, we do not even know which items were the ones that could not be written, right?

**Comment by fxn** [comment]
Hmmm, maybe in some cases, I had

```
{:error, {"ValidationException", "Provided list of item keys contains duplicates"}}
```

in mind.

**Comment by darrenklein** [comment]
Offhand, I'm not sure what the unprocessed items would look like in the case of a batch write attempt, but in a batch read you'd get something back like

```
%{"model_name" => %{"Keys" => [%{"id" => %{"S" => "1234"}},%{"id" => %{"S" => "abcd"}}]}}
```
